baseURL = "https://cuidezhu.github.io/"
languageCode = "en-us"
title = "老崔博客"
theme = "elephants"

[author]
  primary = "Dezhu Cui"

[params]
  Description = "Reading, Blog, Thought"
  
[permalinks]
  post = "/:year/:slug"